---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8snginxapp
  namespace: fluxcd-test
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/mkamran1411/fluxcd-nginx-deploy.git

